In [6]:
# NumPy提供了两种基本的对象：ndarray和ufunc
# ndarray是存储单一数据类型的多维数组
# ufunc则是能够对数据进行处理的函数

import numpy as np

# 使用python数据结构来初始化ndarray
a = np.array([1, 2, 3, 4])      # 列表
b = np.array((5, 6, 7, 8))      # 元祖
c = np.array([[1, 2, 3, 4], [4, 5, 6, 7], [7, 8, 9, 10]])       # 二维列表
d = np.array(15)
print("a=", a)
print("b=", b)
print("c=", c)
print("c.shape=", c.shape)
print("d=", d)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [10]:
# 直接更改数组的shape，将3x4的数组改为4x3，并不是对数组进行转置
# 而只是改变每个轴的大小，因为元素在内存中的位置没有发生改变
# 这种方式不会产生新的数组
c.shape = 4,3
print("c=", c)

c= [[ 1  2  3]
 [ 4  4  5]
 [ 6  7  7]
 [ 8  9 10]]


In [11]:
# 进行维度转换
# data.reshape(rows, cols)，转换成rows行，cols列
# -1 表是默认计算，reshape(3, -1)表示三行，列数自动计算
# reshape(-1, 5)，表示5列，行数自动计算
# 这种方式将返回一个改变了shape的新数组，原数组的大小保持不变
data = d.reshape(3, 5)
print("data=", data)
print("d=", data)

# d与data共享数据存储的内存区域，因此改变其中一个的值，另外一个数组也会被修改
d[1] = 100      # 将第一行的数据全部设置成100
print("data=", data)

data= [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
d= [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
data= [[  0   1   2   3   4]
 [100 100 100 100 100]
 [ 10  11  12  13  14]]


In [12]:
# 数据类型
print("d.dtype=", d.dtype)

# 新建数组是指定数据类型
np.array([[1, 2, 3, 4], [4, 5, 6, 7], [7, 8, 9, 10]], dtype=np.float)

d.dtype= int64


array([[ 1.,  2.,  3.,  4.],
       [ 4.,  5.,  6.,  7.],
       [ 7.,  8.,  9., 10.]])

In [13]:
# 利用arange方法创建数组
# 指定开始值，结束值，与步长来创建一维数组（不包含结束值）
np.arange(0, 1, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [15]:
# linspace
# 指定开始值，结束值，元素个数
print(np.linspace(0, 1, 9))

# 不包含结束值
print(np.linspace(0, 1, 9, endpoint=False))

[0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875 1.   ]
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889]


In [16]:
# logspace
# 与linspace类似，不过创建的是等比数列
# 下面的例子会生成10^0到10^2之间包含9个元素的等比数列
np.logspace(0, 2, 9)

array([  1.        ,   1.77827941,   3.16227766,   5.62341325,
        10.        ,  17.7827941 ,  31.6227766 ,  56.23413252,
       100.        ])

In [19]:
# 从字节序列创建数组
s = "abcdefghijklmn"
np.frombuffer(s.encode(), dtype=np.int8)


array([ 97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109,
       110], dtype=int8)

In [6]:


# 生成一个4x4的随机数组
np.random.rand(4,4)

# numpy中包含两种数据类型，矩阵与数组（matrix和array），他们都可以用来处理行列表示的数字元素
# 虽然他们看起来很相似，不过对他们进行相同的数学运算可能会产生不同的结果
# 其中numpy中的matrix与MATLAB中的matrices等价
# 下面是将随机数组转换成一个矩阵
randMat = np.mat(np.random.rand(4,4))

In [7]:
# 矩阵的一些运算

# 求反
invRandMat = randMat.I

# 矩阵乘法
myEye = invRandMat * randMat

# 上面得到的结果应该是一个单位矩阵，除了对角线元素是１，4x4矩阵的其他元素应该全是０
# 矩阵上面还留下一些非常小的元素，这是计算机处理误差产生的结果
# 下面语句得到误差值
myEye - np.eye(4)

matrix([[ 0.00000000e+00, -5.55111512e-17, -2.22044605e-16,
          2.77555756e-17],
        [-5.55111512e-17, -1.11022302e-16, -5.55111512e-17,
         -1.11022302e-16],
        [-1.59594560e-16,  0.00000000e+00,  0.00000000e+00,
         -1.66533454e-16],
        [ 1.11022302e-16,  1.11022302e-16,  1.11022302e-16,
          2.22044605e-16]])